---

- name: test if gitlab_version is set correctly
  ansible.builtin.assert:
    that:
      - gitlab_version is defined
      - gitlab_version is string
    quiet: yes

- name: test if gitlab_external_url is set correctly
  ansible.builtin.assert:
    that:
      - gitlab_external_url is defined
      - gitlab_external_url is string
    quiet: yes

- name: test if gitlab_rails_time_zone is set correctly
  ansible.builtin.assert:
    that:
      - gitlab_rails_time_zone is defined
      - gitlab_rails_time_zone is string
    quiet: yes

- name: test if gitlab_distribution is set correctly
  ansible.builtin.assert:
    that:
      - gitlab_distribution is defined
      - gitlab_distribution is string
      - gitlab_distribution in [ "community", "enterprise" ]
    quiet: yes

- name: test if gitlab_cleanup_ruby is set correctly
  ansible.builtin.assert:
    that:
      - gitlab_cleanup_ruby is defined
      - gitlab_cleanup_ruby is boolean
    quiet: yes

- name: test if gitlab_roles is set correctly
  ansible.builtin.assert:
    that:
      - gitlab_roles is iterable
    quiet: yes
  when:
    - gitlab_roles is defined

- name: test if item in gitlab_roles is set correctly
  ansible.builtin.assert:
    that:
      - item in [ "redis_sentinel_role", "redis_master_role", "redis_replica_role", "geo_primary_role", "geo_secondary_role", "postgres_role", "consul_role", "application_role", "monitoring_role" ]
    quiet: yes
  loop: "{{ gitlab_roles }}"
  when:
    - gitlab_roles is defined

- name: test if gitlab_default_theme is set correctly
  ansible.builtin.assert:
    that:
      - gitlab_default_theme is defined
      - gitlab_default_theme is string
      - gitlab_default_theme in [ "indigo", "dark", "light", "blue", "green", "lightindigo", "lightblue", "lightgreen", "red", "lightred" ]
    quiet: yes

- name: test if gitlab_default_projects_feature_* are set correctly
  ansible.builtin.assert:
    that:
      - gitlab_default_projects_features_issues is defined
      - gitlab_default_projects_features_issues is boolean
      - gitlab_default_projects_features_merge_requests is defined
      - gitlab_default_projects_features_merge_requests is boolean
      - gitlab_default_projects_features_wiki is defined
      - gitlab_default_projects_features_wiki is boolean
      - gitlab_default_projects_features_snippets is defined
      - gitlab_default_projects_features_snippets is boolean
      - gitlab_default_projects_features_builds is defined
      - gitlab_default_projects_features_builds is boolean
      - gitlab_default_projects_features_container_registry is defined
      - gitlab_default_projects_features_container_registry
    quiet: yes

- name: test if gitlab_rails_ldap_enabled is set correctly
  ansible.builtin.assert:
    that:
      - gitlab_rails_ldap_enabled is defined
      - gitlab_rails_ldap_enabled is boolean
    quiet: yes

- name: test if gitlab_rails_prevent_ldap_sign_in is set correctly
  ansible.builtin.assert:
    that:
      - gitlab_rails_prevent_ldap_sign_in is defined
      - gitlab_rails_prevent_ldap_sign_in is boolean
    quiet: yes

- name: test if gitlab_rails_ldap_servers is set correctly
  ansible.builtin.assert:
    that:
      - gitlab_rails_ldap_servers is iterable
    quiet: yes
  when:
    - gitlab_rails_ldap_enabled

- name: test if item in gitlab_rails_ldap_servers is set correctly
  ansible.builtin.assert:
    that:
      - item.name is defined
      - item.name is string
      - item.label is defined
      - item.port is defined
      - item.port is number
      - item.uid is defined
      - item.uid is string
      - item.bind_dn is defined
      - item.bind_dn is string
      - item.password is defined
      - item.password is string
      - item.encryption is defined
      - item.encryption is string
      - item.encryption in [ "plain", "simple_tls", "start_tls" ]
      - item.verify_certificates is defined
      - item.verify_certificates is boolean
      - item.smartcard_auth is defined
      - item.smartcard_auth is boolean
      - item.active_directory is defined
      - item.active_directory is boolean
      - item.allow_username_or_email_login is defined
      - item.allow_username_or_email_login is boolean
      - item.lowercase_usernames is defined
      - item.lowercase_usernames is boolean
      - item.block_auto_created_users is defined
      - item.block_auto_created_users is boolean
      - item.base is defined
      - item.base is string
      - item.user_filter is defined
      - item.user_filter is string
    quiet: yes
  loop: "{{ gitlab_rails_ldap_servers }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - gitlab_rails_ldap_enabled

- name: test if enterprise item in gitlab_rails_ldap_servers is set correctly
  ansible.builtin.assert:
    that:
      - item.group_base is defined
      - item.group_base is string
      - item.admin_group is defined
      - item.admin_group is string
      - item.sync_ssh_keys is defined
      - item.sync_ssh_keys is boolean
    quiet: yes
  loop: "{{ gitlab_rails_ldap_servers }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - gitlab_rails_ldap_enabled

- name: test if enterprise item in gitlab_rails_ldap_servers is not set
  ansible.builtin.assert:
    that:
      - item.group_base is not defined
      - item.group_base is not string
      - item.admin_group is not defined
      - item.admin_group is not string
      - item.sync_ssh_keys not is defined
      - item.sync_ssh_keys not is boolean
    quiet: yes
  loop: "{{ gitlab_rails_ldap_servers }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - gitlab_rails_ldap_server is defined
    - gitlab_distribution == "community"

##########

- name: test if gitlab_rails_manage_backup_path is set correctly
  ansible.builtin.assert:
    that:
      - gitlab_rails_manage_backup_path is boolean
    quiet: yes
  when:
    - gitlab_rails_manage_backup_path is defined

- name: test if gitlab_rails_backup_path is set correctly
  ansible.builtin.assert:
    that:
      - gitlab_rails_backup_path is string
    quiet: yes
  when:
    - gitlab_rails_backup_path is defined

- name: test if gitlab_rails_backup_gitaly_backup_path is set correctly
  ansible.builtin.assert:
    that:
      - gitlab_rails_backup_gitaly_backup_path is string
    quiet: yes
  when:
    - gitlab_rails_backup_gitaly_backup_path is defined

- name: test if gitlab_rails_backup_archive_permissions is set correctly
  ansible.builtin.assert:
    that:
      - gitlab_rails_backup_archive_permissions is string
    quiet: yes
  when:
    - gitlab_rails_backup_archive_permissions is defined

- name: test if gitlab_rails_backup_pg_schema is set correctly
  ansible.builtin.assert:
    that:
      - gitlab_rails_backup_pg_schema is string
    quiet: yes
  when:
    - gitlab_rails_backup_pg_schema is defined

- name: test if gitlab_rails_backup_keep_time is set correctly
  ansible.builtin.assert:
    that:
      - gitlab_rails_backup_keep_time is number
    quiet: yes
  when:
    - gitlab_rails_backup_keep_time is defined

- name: test if items in gitlab_rails_backup_upload_connection is set correctly
  ansible.builtin.assert:
    that:
      - gitlab_rails_backup_upload_connection is mapping
      - gitlab_rails_backup_upload_connection.provider is defined
      - gitlab_rails_backup_upload_connection.provider is string
      - gitlab_rails_backup_upload_connection.provider in [ "AWS", "AzureRM", "Google", "Local" ]
    quiet: yes
  when:
    - gitlab_rails_backup_upload_connection is defined

- name: test if aws items in gitlab_rails_backup_upload_connection is set correctly
  ansible.builtin.assert:
    that:
      - gitlab_rails_backup_upload_connection.aws_access_key_id is defined
      - gitlab_rails_backup_upload_connection.aws_access_key_id is string
      - gitlab_rails_backup_upload_connection.aws_secret_access_key is defined
      - gitlab_rails_backup_upload_connection.aws_secret_access_key is string
      - gitlab_rails_backup_upload_connection.use_iam_profile is defined
      - gitlab_rails_backup_upload_connection.use_iam_profile is boolean
    quiet: yes
  when:
    - gitlab_rails_backup_upload_connection is defined
    - gitlab_rails_backup_upload_connection.provider == "AWS"

- name: test if azure items in gitlab_rails_backup_upload_connection is set correctly
  ansible.builtin.assert:
    that:
      - gitlab_rails_backup_upload_connection.azure_storage_account_name is defined
      - gitlab_rails_backup_upload_connection.azure_storage_account_name is string
      - gitlab_rails_backup_upload_connection.azure_storage_access_key is defined
      - gitlab_rails_backup_upload_connection.azure_storage_access_key is string
    quiet: yes
  when:
    - gitlab_rails_backup_upload_connection is defined
    - gitlab_rails_backup_upload_connection.provider == "AzureRM"

- name: test if azure_storage_domain in gitlab_rails_backup_upload_connection is set correctly
  ansible.builtin.assert:
    that:
      - gitlab_rails_backup_upload_connection.azure_storage_domain is boolean
    quiet: yes
  when:
    - gitlab_rails_backup_upload_connection is defined
    - gitlab_rails_backup_upload_connection.azure_storage_domain is defined

- name: test if google items in gitlab_rails_backup_upload_connection is set correctly
  ansible.builtin.assert:
    that:
      - gitlab_rails_backup_upload_connection.google_storage_access_key_id is defined
      - gitlab_rails_backup_upload_connection.google_storage_access_key_id is string
      - gitlab_rails_backup_upload_connection.google_storage_secret_access_key is defined
      - gitlab_rails_backup_upload_connection.google_storage_secret_access_key is string
    quiet: yes
  when:
    - gitlab_rails_backup_upload_connection is defined
    - gitlab_rails_backup_upload_connection.provider == "Google"

- name: test if gitlab_rails_backup_upload_connection is set correctly
  ansible.builtin.assert:
    that:
      - gitlab_rails_backup_upload_connection.local_root is defined
      - gitlab_rails_backup_upload_connection.local_root is string
    quiet: yes
  when:
    - gitlab_rails_backup_upload_connection is defined
    - gitlab_rails_backup_upload_connection.provider == "Local"

- name: test if gitlab_rails_backup_upload_remote_directory is set correctly
  ansible.builtin.assert:
    that:
      - gitlab_rails_backup_upload_remote_directory is string
    quiet: yes
  when:
    - gitlab_rails_backup_upload_remote_directory is defined

- name: test if gitlab_rails_backup_multipart_chunk_size is set correctly
  ansible.builtin.assert:
    that:
      - gitlab_rails_backup_multipart_chunk_size is number
    quiet: yes
  when:
    - gitlab_rails_backup_multipart_chunk_size is defined

- name: test if gitlab_rails_backup_encryption is set correctly
  ansible.builtin.assert:
    that:
      - gitlab_rails_backup_encryption is string
    quiet: yes
  when:
    - gitlab_rails_backup_encryption is defined

- name: test if gitlab_rails_backup_encryption_key is set correctly
  ansible.builtin.assert:
    that:
      - gitlab_rails_backup_encryption_key is string
    quiet: yes
  when:
    - gitlab_rails_backup_encryption_key is defined

- name: test if gitlab_rails_backup_upload_storage_options is set correctly
  ansible.builtin.assert:
    that:
      - gitlab_rails_backup_upload_storage_options is defined
      - gitlab_rails_backup_upload_storage_options is mapping
      - gitlab_rails_backup_upload_storage_options.server_side_encryption is defined
      - gitlab_rails_backup_upload_storage_options.server_side_encryption is string
      - gitlab_rails_backup_upload_storage_options.server_side_encryption_kms_key_id is defined
      - gitlab_rails_backup_upload_storage_options.server_side_encryption_kms_key_id is string
    quiet: yes
  when:
    - gitlab_rails_backup_encryption_key is defined

- name: test if gitlab_rails_backup_storage_class is set correctly
  ansible.builtin.assert:
    that:
      - gitlab_rails_backup_storage_class is string
      - gitlab_rails_backup_storage_class in [ "REDUCED_REDUNDANCY", "STANDARD", "STANDARD_IA" ]
    quiet: yes
  when:
    - gitlab_rails_backup_storage_class is defined

- name: test if gitlab_rails_env is set correctly
  ansible.builtin.assert:
    that:
      - gitlab_rails_env is mapping
    quiet: yes
  when:
    - gitlab_rails_env is defined
